# Generated by Django 4.2.7 on 2024-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_report_remove_newsarticle_author_delete_reportform'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu')], default='soumis', max_length=20),
        ),
    ]
