# Generated by Django 4.2.7 on 2024-01-23 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0007_report_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('submitted', 'Soumis'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
